from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Text, Enum as SAEnum, Boolean, JSON
from sqlalchemy.orm import relationship
import enum
from datetime import datetime, timezone

from app.models.base import Base, TimestampMixin


class AIConversation(TimestampMixin, Base):
    """Factory Copilot chat conversations."""
    __tablename__ = "ai_conversations"

    factory_id = Column(Integer, ForeignKey("factories.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String)
    context_line_id = Column(Integer, ForeignKey("production_lines.id"), nullable=True)

    messages = relationship("AIMessage", back_populates="conversation", order_by="AIMessage.created_at")


class AIMessage(TimestampMixin, Base):
    __tablename__ = "ai_messages"

    conversation_id = Column(Integer, ForeignKey("ai_conversations.id"), nullable=False)
    role = Column(String, nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    tokens_used = Column(Integer)
    data_context = Column(JSON)  # JSON snapshot of factory data used for this response

    conversation = relationship("AIConversation", back_populates="messages")


class AISuggestionStatus(str, enum.Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    IMPLEMENTED = "implemented"


class AIKaizenSuggestion(TimestampMixin, Base):
    """Auto Kaizen suggestions generated by AI."""
    __tablename__ = "ai_kaizen_suggestions"

    factory_id = Column(Integer, ForeignKey("factories.id"), nullable=False)
    production_line_id = Column(Integer, ForeignKey("production_lines.id"), nullable=True)

    suggestion_type = Column(String, nullable=False)  # "oee", "quality", "downtime", "smed", "general"
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    expected_impact = Column(Text)
    lean_tool = Column(String)  # e.g. "SMED", "5S", "TPM", "Kanban"
    confidence = Column(Float)  # 0-1
    priority_score = Column(Float)  # calculated priority

    status = Column(SAEnum(AISuggestionStatus), default=AISuggestionStatus.PENDING)
    reviewed_by_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    kaizen_item_id = Column(Integer, ForeignKey("kaizen_items.id"), nullable=True)

    data_snapshot = Column(JSON)  # The data that triggered this suggestion
